### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by andutzu7** [ceofil/ytb-playlist-sort#3]
Te rog sa schimbi licenta. Licenta MIT e cea mai proasta licenta open source!!!! Schimba cu GPL3 sau Apache

**Comment by ceofil** [comment]
Gata serifule 
https://youtube.com/clip/UgkxDwKwn7GJpM5v3ZX2tzsUtXU4QjhlTcZ9?si=w4JCREHnP0WedWHc
